/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PartnerOnboardRouteImport } from './routes/partner.onboard'
import { Route as PartnerLoginRouteImport } from './routes/partner.login'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminEarningsRouteImport } from './routes/admin.earnings'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PartnerOnboardRoute = PartnerOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerLoginRoute = PartnerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEarningsRoute = AdminEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/request': typeof RequestRoute
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboard': typeof PartnerOnboardRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboard': typeof PartnerOnboardRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/partner': typeof PartnerRouteWithChildren
  '/request': typeof RequestRoute
  '/admin/earnings': typeof AdminEarningsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/partner/login': typeof PartnerLoginRoute
  '/partner/onboard': typeof PartnerOnboardRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/partner'
    | '/request'
    | '/admin/earnings'
    | '/admin/partners'
    | '/admin/properties'
    | '/admin/redirects'
    | '/admin/settings'
    | '/partner/login'
    | '/partner/onboard'
    | '/admin/'
    | '/partner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request'
    | '/admin/earnings'
    | '/admin/partners'
    | '/admin/properties'
    | '/admin/redirects'
    | '/admin/settings'
    | '/partner/login'
    | '/partner/onboard'
    | '/admin'
    | '/partner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/partner'
    | '/request'
    | '/admin/earnings'
    | '/admin/partners'
    | '/admin/properties'
    | '/admin/redirects'
    | '/admin/settings'
    | '/partner/login'
    | '/partner/onboard'
    | '/admin/'
    | '/partner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PartnerRoute: typeof PartnerRouteWithChildren
  RequestRoute: typeof RequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/partner/onboard': {
      id: '/partner/onboard'
      path: '/onboard'
      fullPath: '/partner/onboard'
      preLoaderRoute: typeof PartnerOnboardRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/login': {
      id: '/partner/login'
      path: '/login'
      fullPath: '/partner/login'
      preLoaderRoute: typeof PartnerLoginRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/earnings': {
      id: '/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AdminEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEarningsRoute: typeof AdminEarningsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEarningsRoute: AdminEarningsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnerRouteChildren {
  PartnerLoginRoute: typeof PartnerLoginRoute
  PartnerOnboardRoute: typeof PartnerOnboardRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerLoginRoute: PartnerLoginRoute,
  PartnerOnboardRoute: PartnerOnboardRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PartnerRoute: PartnerRouteWithChildren,
  RequestRoute: RequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
